### ISSUE TITLE
Add Instructional Video

### ISSUE THREAD

**Issue by YoussefNabilNew** [tnkemdilim/Money-To-Words-Converter#11]
Could you please make an instructional video on how to use ```Money-To-Words-Converter```.

Thank you so much

**Comment by toksdotdev** [comment]
Hello @YoussefNabilNew,

I'll try to come up with an instructional video ASAP (within my free time).

Although a simple example can be found [here](https://github.com/TNkemdilim/Money-To-Words-Converter/#basic-usage).

Please feel free to reach out to me for further clarifications.

**Comment by YoussefNabilNew** [comment]
actually i try it ,but it does not work.the video will be more easy.thank you so much for your time .i appreciate your work.

**Comment by toksdotdev** [comment]
Thank you so much.

I just discovered that the examples were missing something. I was using class ```Conveter``` instead of ```Converter```.

This has been fixed in this commit [f3c41bb](https://github.com/TNkemdilim/Money-To-Words-Converter/commit/f3c41bb719ec3c35f063ded1e7751b9a27298a98).

**Please copy the recent [example](https://github.com/TNkemdilim/Money-To-Words-Converter/#basic-usage), and try again.**

Although I'll still make a usage video for you.

**Comment by YoussefNabilNew** [comment]
thanks a  lot

**Comment by YoussefNabilNew** [comment]
Please i need some help.
this is what it gives me:

Fatal error: Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found in C:\xampp\htdocs\convert\EnglishConversionTest.php:15 Stack trace: #0 {main} thrown in C:\xampp\htdocs\convert\EnglishConversionTest.php on line 15

**Comment by toksdotdev** [comment]
You have to install the composer PHPUnit test. Run `composer install` on the current repository.

**Comment by YoussefNabilNew** [comment]
how can i do that ?

**Comment by toksdotdev** [comment]
I just created an example project for you, see [Example](https://github.com/TNkemdilim/Money-To-Words-Converter/tree/master/example).

**Comment by YoussefNabilNew** [comment]
thank you so much .i appreciate Your help.I wish you a successful  in your life to help us .thank you again.
have a nice day.

**Comment by YoussefNabilNew** [comment]
thank you so much

**Comment by toksdotdev** [comment]
Thank you so much. I really appreciate your kind remark. God bless.
