### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by spagu** [tnkemdilim/Money-To-Words-Converter#21]
An exception has been thrown during the rendering of a template ("Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=auto&tl=ar&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=388153.253767` resulted in a `400 Bad Request` response: <!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...) ").

 I did all of the examples from this library. It just does not work.

**Comment by TNkemdilim** [comment]
Hello @spagu ,

So sorry about the error. I'll look into it today and work on a fix.

**Comment by toksdotdev** [comment]
Hello @spagu,

Apologies for the delayed response.

Currently, this library relies on [stichoza/google-translate-php](https://github.com/Stichoza/google-translate-php#known-limitations) which could result in periodic `400 Bad Request` as highlighted [here](https://github.com/Stichoza/google-translate-php#known-limitations) and [here](https://github.com/tnkemdilim/Money-To-Words-Converter/issues/21).

If the reliability of the service is important, you could try out a managed version API service I run at [Tuforty](https://tuforty.com).

Thanks a lot.
