### ISSUE TITLE
Remove var_dump

### ISSUE THREAD

**Issue by chaikovskyia** [tnkemdilim/Money-To-Words-Converter#25]
When installing through composer the package has var_dump in \TNkemdilim\MoneyToWords\Converter::_setMoney on line 146. 
I'm using the extension to generate a pdf file and the line breaks PDF.

Direct link from composer.lock: https://api.github.com/repos/TNkemdilim/Money-To-Words-Converter/zipball/731c781bd1fe433d1e521a182d8b970ef3d66047

**Comment by toksdotdev** [comment]
My honest apologies for the delayed response.

Please could you check that you're on the latest version?

The latest version doesn't make use of `var_dump`.
