### ISSUE TITLE
unable to load under linux, on windows works fine

### ISSUE THREAD

**Issue by ghost** [tnkemdilim/Money-To-Words-Converter#4]
installed on openSUSE Server Leap 42.3

when run in app following occurs:

Fatal error: Class 'MoneyToWords\MoneyToWordsConverter' not found in /srv/www/htdocs/realoffer/dashboard.php on line 423

but same code is working fine on windows dev machine under phpED IDE

coded as:

  require 'vendor/autoload.php';
  use MoneyToWords\MoneyToWordsConverter;
  
  $Testmoney = 1250000;
  $converter = new MoneyToWordsConverter($Testmoney, "dollars");
  echo ($converter->Convert());  

directory structures identical under linux and windows

**Comment by toksdotdev** [comment]
I'll try reproduce the error,  and give a fix shortly.

**Comment by toksdotdev** [comment]
Sorry, do you mind if you post the full code.

Also, what are you using to auto-load the files e.g. composer etc.

Also if try to switch between ```<?php ... ?>``` to ```<? ... ```. As some servers do not recognize both.

Lastly, I'm so sorry for the inconvenience this might have caused.

**Comment by toksdotdev** [comment]
Since I haven't gotten a response, I'll kindly close the issue.
